theme: jekyll-theme-merlot
highlighter: rouge
name: Karlie Le
description: An amateur approach to programming
url: https://karliele.github.io/Karlie-Le/
lsi: false

exclude: [README.md]

permalink: pretty
