# Setup
title: Karlie's Blog      
description:      An amateur approach to programming
baseurl:      ""
paginate:  4   1
locale:       "en"

# About/contact
author:
  name:       Karlie Le
  url:     https://karliele.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
