# Setup
title: Karlie's Blog       Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:  4   1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:     https://karliele.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown