# Setup
title: lilbookcorner      
description:      ONLINE LIBRARY
baseurl:      ""
paginate:  4   1
locale:       "en"

# About/contact
author:
  name:      
  url:     https://lilbookcorner.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
